#!/usr/bin/env python3

from __future__ import annotations

import sys
from pathlib import Path

from package_graph import (
    REPO_ROOT,
    build_dependency_graph,
    feature_dependencies,
    high_coupling_packages,
    mutual_coupling_pairs,
)


DOC_PATH = REPO_ROOT / "docs" / "PACKAGE_DEPENDENCY_INVENTORY.md"
BEGIN_MARKER = "<!-- BEGIN GENERATED DEPENDENCY INVENTORY -->"
END_MARKER = "<!-- END GENERATED DEPENDENCY INVENTORY -->"


def render_generated_section() -> str:
    graph = build_dependency_graph()
    high_coupling = high_coupling_packages(graph)
    mutual_pairs = mutual_coupling_pairs(graph)
    core_feature_dependencies = feature_dependencies(graph, "artbeat_core")

    lines: list[str] = [
        "## Purpose",
        "",
        "Record the current package-to-package dependency graph so architecture work can",
        "start from the actual repo state.",
        "",
        "Source:",
        "",
        "- `packages/*/pubspec.yaml`",
        "- generated by `tools/architecture/generate_package_dependency_inventory.py`",
        "",
        "## Current Graph",
        "",
    ]

    for package_name, dependencies in graph.items():
        lines.extend(
            [
                f"### `{package_name}`",
                "",
                "Depends on:",
                "",
            ]
        )

        if dependencies:
            lines.extend([f"- `{dependency}`" for dependency in dependencies])
        else:
            lines.append("- no sibling feature packages")

        lines.append("")

    lines.extend(
        [
            "## Current Rule Alignment",
            "",
            "Target rules from `docs/DEPENDENCY_RULES.md`:",
            "",
            "- `artbeat_core` should not depend on feature packages",
            "- feature packages should not depend on other feature packages by default",
            "",
            "### `artbeat_core` base-layer status",
            "",
            f"`artbeat_core` currently depends on {len(core_feature_dependencies)} sibling feature packages.",
            "",
        ]
    )

    if core_feature_dependencies:
        lines.extend(
            [
                "Active manifest-level violation:",
                "",
            ]
        )
        lines.extend([f"- `{dependency}`" for dependency in core_feature_dependencies])
        lines.append("")
    else:
        lines.extend(
            [
                "Manifest-level status: aligned with the base-layer rule.",
                "",
            ]
        )

    lines.extend(
        [
            "### Feature-to-feature dependency hotspots",
            "",
        ]
    )

    if high_coupling:
        lines.extend(
            [
                "These packages currently depend on 2 or more other feature packages:",
                "",
            ]
        )
        lines.extend([f"- `{package_name}`" for package_name in high_coupling])
        lines.append("")
    else:
        lines.extend(
            [
                "No packages currently depend on 2 or more other feature packages.",
                "",
            ]
        )

    lines.extend(
        [
            "### Mutual coupling",
            "",
        ]
    )

    if mutual_pairs:
        lines.extend(
            [
                "Manifest-level mutual coupling is still present in:",
                "",
            ]
        )
        lines.extend([f"- `{left}` <-> `{right}`" for left, right in mutual_pairs])
        lines.append("")
    else:
        lines.extend(
            [
                "No manifest-level mutual coupling is currently present.",
                "",
                "Remaining risk is more likely to come from app-shell orchestration and",
                "service ownership than from package-manifest cycles.",
                "",
            ]
        )

    return "\n".join(lines).rstrip()


def update_document(document_text: str, generated_section: str) -> str:
    begin_index = document_text.find(BEGIN_MARKER)
    end_index = document_text.find(END_MARKER)

    if begin_index == -1 or end_index == -1 or begin_index >= end_index:
        raise ValueError(
            "Dependency inventory markers are missing or malformed in docs/PACKAGE_DEPENDENCY_INVENTORY.md."
        )

    replacement = f"{BEGIN_MARKER}\n{generated_section}\n{END_MARKER}"
    return (
        document_text[:begin_index]
        + replacement
        + document_text[end_index + len(END_MARKER):]
    )


def main(argv: list[str]) -> int:
    check_mode = len(argv) > 1 and argv[1] == "--check"
    current_text = DOC_PATH.read_text()
    expected_text = update_document(current_text, render_generated_section())

    if check_mode:
        if current_text != expected_text:
            print("Package dependency inventory is out of date.")
            print("Run: python3 tools/architecture/generate_package_dependency_inventory.py")
            return 1
        print("Package dependency inventory is up to date.")
        return 0

    DOC_PATH.write_text(expected_text)
    print(f"Updated {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
