#!/usr/bin/env python3
"""Generate a localization parity report from assets/translations/*.json."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TRANSLATIONS_DIR = ROOT / "assets" / "translations"
OUTPUT_PATH = TRANSLATIONS_DIR / "missing_keys.md"
SOURCE_LOCALE = "en"


def load_locale(path: Path) -> dict[str, str]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path} does not contain a top-level JSON object")
    return data


def main() -> None:
    locale_paths = sorted(
        path
        for path in TRANSLATIONS_DIR.glob("*.json")
        if path.name != "missing_keys.md"
    )
    source_path = TRANSLATIONS_DIR / f"{SOURCE_LOCALE}.json"
    if source_path not in locale_paths:
        raise FileNotFoundError(f"Source locale not found: {source_path}")

    source_data = load_locale(source_path)
    source_keys = set(source_data)

    lines: list[str] = []
    lines.append("# Localization Missing Keys")
    lines.append("")
    lines.append(f"Source locale: `{SOURCE_LOCALE}.json`")
    lines.append("")
    lines.append("Compared files:")
    for path in locale_paths:
        lines.append(f"- `{path.name}`")
    lines.append("")

    for path in locale_paths:
        if path == source_path:
            continue

        locale_data = load_locale(path)
        locale_keys = set(locale_data)
        missing = sorted(source_keys - locale_keys)
        extra = sorted(locale_keys - source_keys)

        lines.append(f"## {path.name}")
        lines.append("")
        lines.append(f"- Missing keys: {len(missing)}")
        lines.append(f"- Extra keys: {len(extra)}")
        lines.append("")

        if missing:
            lines.append("Missing:")
            for key in missing:
                lines.append(f"- `{key}`")
            lines.append("")

        if extra:
            lines.append("Extra:")
            for key in extra:
                lines.append(f"- `{key}`")
            lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append(
        "This file is generated by `python3 tools/localization/report_missing_keys.py`."
    )
    lines.append(
        "Do not hand-edit this report unless you are also changing the generator."
    )
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote localization report to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
