#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Arabic Translation Script - Mega Pass 5
Focus: Dates, Times, Numbers, Units, and Common Phrases
"""

import json
import re

# Mega Pass 5: Dates, Times, Numbers, Units, Common Phrases
AR_MEGA_TRANSLATIONS_5 = {
    # Date & Time
    "Today": "اليوم",
    "Tomorrow": "غدًا",
    "Yesterday": "أمس",
    "Now": "الآن",
    "Just now": "الآن فقط",
    "Recently": "مؤخرًا",
    "Soon": "قريبًا",
    "Later": "لاحقًا",
    "Always": "دائمًا",
    "Never": "أبدًا",
    "Morning": "الصباح",
    "Afternoon": "بعد الظهر",
    "Evening": "المساء",
    "Night": "الليل",
    "Midnight": "منتصف الليل",
    "Noon": "الظهر",
    "AM": "صباحًا",
    "PM": "مساءً",
    "Sunday": "الأحد",
    "Monday": "الاثنين",
    "Tuesday": "الثلاثاء",
    "Wednesday": "الأربعاء",
    "Thursday": "الخميس",
    "Friday": "الجمعة",
    "Saturday": "السبت",
    "January": "يناير",
    "February": "فبراير",
    "March": "مارس",
    "April": "أبريل",
    "May": "مايو",
    "June": "يونيو",
    "July": "يوليو",
    "August": "أغسطس",
    "September": "سبتمبر",
    "October": "أكتوبر",
    "November": "نوفمبر",
    "December": "ديسمبر",
    "Day": "يوم",
    "Days": "أيام",
    "Week": "أسبوع",
    "Weeks": "أسابيع",
    "Month": "شهر",
    "Months": "أشهر",
    "Year": "سنة",
    "Years": "سنوات",
    "Hour": "ساعة",
    "Hours": "ساعات",
    "Minute": "دقيقة",
    "Minutes": "دقائق",
    "Second": "ثانية",
    "Seconds": "ثوانٍ",
    "{count} ago": "منذ {count}",
    "{count} from now": "بعد {count}",
    "in {time}": "خلال {time}",
    "{time} ago": "منذ {time}",
    "Last {period}": "{period} الماضي",
    "Next {period}": "{period} القادم",
    "This {period}": "هذا {period}",
    "Every {period}": "كل {period}",
    "Once": "مرة واحدة",
    "Twice": "مرتين",
    "Daily": "يوميًا",
    "Weekly": "أسبوعيًا",
    "Monthly": "شهريًا",
    "Yearly": "سنويًا",
    "Hourly": "كل ساعة",
    "Recurring": "متكرر",
    "One-time": "مرة واحدة",
    "Repeat": "تكرار",
    "Does not repeat": "لا يتكرر",
    "Custom": "مخصص",
    "All Day": "طوال اليوم",
    "Starts": "يبدأ",
    "Ends": "ينتهي",
    "From": "من",
    "To": "إلى",
    "Until": "حتى",
    "Since": "منذ",
    "Between": "بين",
    "During": "أثناء",
    "Before": "قبل",
    "After": "بعد",
    "Deadline": "الموعد النهائي",
    "Due Date": "تاريخ الاستحقاق",
    "Reminder": "تذكير",
    
    # Numbers & Quantities
    "All": "الكل",
    "None": "لا شيء",
    "Any": "أي",
    "Some": "بعض",
    "Many": "كثير",
    "Few": "قليل",
    "Several": "عدة",
    "Multiple": "متعدد",
    "Single": "مفرد",
    "Double": "مضاعف",
    "Half": "نصف",
    "Quarter": "ربع",
    "Third": "ثلث",
    "Total": "المجموع",
    "Subtotal": "المجموع الفرعي",
    "Amount": "المبلغ",
    "Count": "العدد",
    "Number": "الرقم",
    "First": "الأول",
    "Last": "الأخير",
    "More": "المزيد",
    "Less": "أقل",
    "Most": "الأكثر",
    "Least": "الأقل",
    "Maximum": "الحد الأقصى",
    "Minimum": "الحد الأدنى",
    "Average": "المتوسط",
    "Percent": "بالمئة",
    "Percentage": "النسبة المئوية",
    "{count} items": "{count} عنصر",
    "{count} results": "{count} نتيجة",
    "No results": "لا توجد نتائج",
    "Show all": "عرض الكل",
    "Show more": "عرض المزيد",
    "Show less": "عرض أقل",
    "Load more": "تحميل المزيد",
    "View all": "عرض الكل",
    "See all": "عرض الكل",
    "See more": "عرض المزيد",
    "See less": "عرض أقل",
    "Expand": "توسيع",
    "Collapse": "طي",
    "Expand all": "توسيع الكل",
    "Collapse all": "طي الكل",
    
    # Units & Measurements
    "Size": "الحجم",
    "Width": "العرض",
    "Height": "الارتفاع",
    "Depth": "العمق",
    "Length": "الطول",
    "Weight": "الوزن",
    "Volume": "الحجم",
    "Area": "المساحة",
    "Distance": "المسافة",
    "Speed": "السرعة",
    "Temperature": "درجة الحرارة",
    "Kilometer": "كيلومتر",
    "Meter": "متر",
    "Centimeter": "سنتيمتر",
    "Millimeter": "ميليمتر",
    "Mile": "ميل",
    "Yard": "ياردة",
    "Foot": "قدم",
    "Inch": "بوصة",
    "Kilogram": "كيلوغرام",
    "Gram": "غرام",
    "Pound": "رطل",
    "Ounce": "أونصة",
    "Liter": "لتر",
    "Milliliter": "ميليلتر",
    "Gallon": "غالون",
    "Celsius": "درجة مئوية",
    "Fahrenheit": "فهرنهايت",
    
    # Common Phrases & Actions
    "Welcome": "مرحبًا",
    "Hello": "مرحبًا",
    "Hi": "مرحبًا",
    "Goodbye": "وداعًا",
    "Bye": "مع السلامة",
    "Thanks": "شكرًا",
    "Thank you": "شكرًا لك",
    "You're welcome": "على الرحب والسعة",
    "Please": "من فضلك",
    "Excuse me": "عذرًا",
    "Sorry": "آسف",
    "No problem": "لا مشكلة",
    "OK": "حسنًا",
    "Okay": "حسنًا",
    "Yes": "نعم",
    "No": "لا",
    "Maybe": "ربما",
    "Sure": "بالتأكيد",
    "Of course": "بالطبع",
    "Absolutely": "بالتأكيد",
    "Definitely": "بالتأكيد",
    "Exactly": "بالضبط",
    "Indeed": "فعلاً",
    "Actually": "في الواقع",
    "Really": "حقًا",
    "Truly": "حقًا",
    "Got it": "فهمت",
    "I understand": "أفهم",
    "I agree": "أوافق",
    "I disagree": "لا أوافق",
    "Agreed": "متفق",
    "Confirmed": "مؤكد",
    "Confirm": "تأكيد",
    "Cancel": "إلغاء",
    "Dismiss": "رفض",
    "Ignore": "تجاهل",
    "Allow": "السماح",
    "Deny": "رفض",
    "Grant": "منح",
    "Revoke": "إلغاء",
    "Enable": "تفعيل",
    "Disable": "تعطيل",
    "Activate": "تنشيط",
    "Deactivate": "إلغاء التنشيط",
    "Turn on": "تشغيل",
    "Turn off": "إيقاف",
    "Open": "فتح",
    "Close": "إغلاق",
    "Start": "بدء",
    "Stop": "إيقاف",
    "Pause": "إيقاف مؤقت",
    "Resume": "استئناف",
    "Play": "تشغيل",
    "Replay": "إعادة التشغيل",
    "Record": "تسجيل",
    "Add": "إضافة",
    "Remove": "إزالة",
    "Delete": "حذف",
    "Update": "تحديث",
    "Modify": "تعديل",
    "Change": "تغيير",
    "Replace": "استبدال",
    "Duplicate": "تكرار",
    "Copy": "نسخ",
    "Cut": "قص",
    "Paste": "لصق",
    "Undo": "تراجع",
    "Redo": "إعادة",
    "Select All": "تحديد الكل",
    "Deselect": "إلغاء التحديد",
    "Move": "نقل",
    "Rename": "إعادة التسمية",
    "Download": "تنزيل",
    "Downloading": "جارٍ التنزيل",
    "Downloaded": "تم التنزيل",
    "Install": "تثبيت",
    "Installing": "جارٍ التثبيت",
    "Installed": "مثبت",
    "Uninstall": "إلغاء التثبيت",
    "Loading": "جارٍ التحميل",
    "Loaded": "تم التحميل",
    "Processing": "جارٍ المعالجة",
    "Processed": "تمت المعالجة",
    "Sending": "جارٍ الإرسال",
    "Sent": "تم الإرسال",
    "Receiving": "جارٍ الاستقبال",
    "Received": "تم الاستقبال",
    "Connecting": "جارٍ الاتصال",
    "Connected": "متصل",
    "Disconnected": "غير متصل",
    "Syncing": "جارٍ المزامنة",
    "Synced": "تمت المزامنة",
    "Updating": "جارٍ التحديث",
    "Updated": "تم التحديث",
    "Saving": "جارٍ الحفظ",
    "Saved": "تم الحفظ",
    "Deleting": "جارٍ الحذف",
    "Deleted": "تم الحذف",
    "Creating": "جارٍ الإنشاء",
    "Created": "تم الإنشاء",
    "Uploading": "جارٍ التحميل",
    "Uploaded": "تم التحميل",
    "Preparing": "جارٍ التحضير",
    "Ready": "جاهز",
    "Waiting": "في الانتظار",
    "Available": "متاح",
    "Coming Soon": "قريبًا",
    "New": "جديد",
    "Popular": "شائع",
    "Trending": "رائج",
    "Recommended": "موصى به",
    "For You": "لك",
    "Discover": "اكتشف",
    "Explore": "استكشف",
    "Learn More": "تعرف على المزيد",
    "Get Started": "ابدأ",
    "Try Now": "جرب الآن",
    "Free": "مجاني",
    "Paid": "مدفوع",
    "Premium": "بريميوم",
    "Pro": "احترافي",
    "Basic": "أساسي",
    "Standard": "قياسي",
    "Advanced": "متقدم",
    "Full": "كامل",
    "Empty": "فارغ",
    "Complete": "مكتمل",
    "Incomplete": "غير مكتمل",
    "Required": "مطلوب",
    "Optional": "اختياري",
    "Mandatory": "إلزامي",
    "Recommended": "موصى به",
    "Suggested": "مقترح",
    "Default": "افتراضي",
    "Custom": "مخصص",
    "Automatic": "تلقائي",
    "Manual": "يدوي",
    "Quick": "سريع",
    "Detailed": "مفصل",
    "Simple": "بسيط",
    "Complex": "معقد",
    "Easy": "سهل",
    "Hard": "صعب",
    "High": "مرتفع",
    "Low": "منخفض",
    "Normal": "عادي",
    "Good": "جيد",
    "Bad": "سيئ",
    "Best": "الأفضل",
    "Worst": "الأسوأ",
    "Better": "أفضل",
    "Worse": "أسوأ",
    "Strong": "قوي",
    "Weak": "ضعيف",
    "Fast": "سريع",
    "Slow": "بطيء",
    "Hot": "حار",
    "Cold": "بارد",
    "Warm": "دافئ",
    "Cool": "بارد",
    "Bright": "مشرق",
    "Dark": "داكن",
    "Light": "فاتح",
    "Heavy": "ثقيل",
    "Old": "قديم",
    "New": "جديد",
    "Recent": "حديث",
    "Latest": "الأحدث",
    "Current": "الحالي",
    "Previous": "السابق",
    "Next": "التالي",
    "Final": "النهائي",
}

def apply_translations():
    """Apply Arabic mega translations pass 5 to ar.json"""
    input_file = '/Users/kristybock/artbeat/assets/translations/ar.json'
    output_file = input_file
    
    print("\n" + "="*60)
    print("Arabic Translation - Mega Pass 5")
    print("Focus: Dates, Times, Numbers, Units, Common Phrases")
    print("="*60 + "\n")
    
    # Load current translations
    with open(input_file, 'r', encoding='utf-8') as f:
        translations = json.load(f)
    
    # Track progress
    applied_count = 0
    
    # Apply translations
    for english_text, arabic_text in AR_MEGA_TRANSLATIONS_5.items():
        # Create bracketed version
        bracketed = f"[{english_text}]"
        
        # Find and replace in translations
        if bracketed in translations.values():
            for key, value in translations.items():
                if value == bracketed:
                    translations[key] = arabic_text
                    applied_count += 1
                    print(f'  ✓ "{english_text}" → "{arabic_text}"')
                    break
    
    # Save updated translations
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(translations, f, ensure_ascii=False, indent=2)
    
    # Count remaining bracketed entries
    remaining = sum(1 for v in translations.values() if v.startswith('[') and v.endswith(']'))
    total = len(translations)
    completed = total - remaining
    percentage = (completed / total * 100) if total > 0 else 0
    
    print(f"\n{'='*60}")
    print("Arabic Translation - Mega Pass 5 Complete")
    print("="*60)
    print(f"Translations applied: {applied_count}")
    print(f"Remaining bracketed entries: {remaining}")
    print(f"Overall progress: {completed}/{total} ({percentage:.1f}%)")
    print(f"File saved: {output_file}")
    print("="*60 + "\n")

if __name__ == "__main__":
    apply_translations()
